version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./logs:/app/logs
      - ./mlruns:/app/mlruns
    env_file:
      - .env
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///mlruns/mlflow.db
    restart: unless-stopped 